//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoClub.ServicioVideoClubPeliculasRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pel", Namespace="http://schemas.datacontract.org/2004/07/ServicioViedoClubPeliculas")]
    [System.SerializableAttribute()]
    public partial class Pel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LdisponibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string actoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string añofilmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string directoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int disponiblesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string duracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string generoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ldisponible {
            get {
                return this.LdisponibleField;
            }
            set {
                if ((object.ReferenceEquals(this.LdisponibleField, value) != true)) {
                    this.LdisponibleField = value;
                    this.RaisePropertyChanged("Ldisponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Loriginal {
            get {
                return this.LoriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.LoriginalField, value) != true)) {
                    this.LoriginalField = value;
                    this.RaisePropertyChanged("Loriginal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string actores {
            get {
                return this.actoresField;
            }
            set {
                if ((object.ReferenceEquals(this.actoresField, value) != true)) {
                    this.actoresField = value;
                    this.RaisePropertyChanged("actores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string añofilm {
            get {
                return this.añofilmField;
            }
            set {
                if ((object.ReferenceEquals(this.añofilmField, value) != true)) {
                    this.añofilmField = value;
                    this.RaisePropertyChanged("añofilm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string directores {
            get {
                return this.directoresField;
            }
            set {
                if ((object.ReferenceEquals(this.directoresField, value) != true)) {
                    this.directoresField = value;
                    this.RaisePropertyChanged("directores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int disponibles {
            get {
                return this.disponiblesField;
            }
            set {
                if ((this.disponiblesField.Equals(value) != true)) {
                    this.disponiblesField = value;
                    this.RaisePropertyChanged("disponibles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string duracion {
            get {
                return this.duracionField;
            }
            set {
                if ((object.ReferenceEquals(this.duracionField, value) != true)) {
                    this.duracionField = value;
                    this.RaisePropertyChanged("duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string genero {
            get {
                return this.generoField;
            }
            set {
                if ((object.ReferenceEquals(this.generoField, value) != true)) {
                    this.generoField = value;
                    this.RaisePropertyChanged("genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloField, value) != true)) {
                    this.tituloField = value;
                    this.RaisePropertyChanged("titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PelFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioViedoClubPeliculas")]
    [System.SerializableAttribute()]
    public partial class PelFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioVideoClubPeliculasRef.IServicioVideoClubPeliculas")]
    public interface IServicioVideoClubPeliculas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVideoClubPeliculas/GetPelicula", ReplyAction="http://tempuri.org/IServicioVideoClubPeliculas/GetPeliculaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VideoClub.ServicioVideoClubPeliculasRef.PelFault), Action="http://tempuri.org/IServicioVideoClubPeliculas/GetPeliculaPelFaultFault", Name="PelFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioViedoClubPeliculas")]
        VideoClub.ServicioVideoClubPeliculasRef.Pel GetPelicula(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVideoClubPeliculas/GetPelicula", ReplyAction="http://tempuri.org/IServicioVideoClubPeliculas/GetPeliculaResponse")]
        System.Threading.Tasks.Task<VideoClub.ServicioVideoClubPeliculasRef.Pel> GetPeliculaAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVideoClubPeliculas/Insertar", ReplyAction="http://tempuri.org/IServicioVideoClubPeliculas/InsertarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VideoClub.ServicioVideoClubPeliculasRef.PelFault), Action="http://tempuri.org/IServicioVideoClubPeliculas/InsertarPelFaultFault", Name="PelFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioViedoClubPeliculas")]
        VideoClub.ServicioVideoClubPeliculasRef.Pel Insertar(int codigo, string titulo, string añofilm, string directores, string actores, string Loriginal, string Ldisponible, string duracion, string genero, int disponibles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVideoClubPeliculas/Insertar", ReplyAction="http://tempuri.org/IServicioVideoClubPeliculas/InsertarResponse")]
        System.Threading.Tasks.Task<VideoClub.ServicioVideoClubPeliculasRef.Pel> InsertarAsync(int codigo, string titulo, string añofilm, string directores, string actores, string Loriginal, string Ldisponible, string duracion, string genero, int disponibles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVideoClubPeliculas/Eliminar", ReplyAction="http://tempuri.org/IServicioVideoClubPeliculas/EliminarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VideoClub.ServicioVideoClubPeliculasRef.PelFault), Action="http://tempuri.org/IServicioVideoClubPeliculas/EliminarPelFaultFault", Name="PelFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioViedoClubPeliculas")]
        VideoClub.ServicioVideoClubPeliculasRef.Pel Eliminar(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVideoClubPeliculas/Eliminar", ReplyAction="http://tempuri.org/IServicioVideoClubPeliculas/EliminarResponse")]
        System.Threading.Tasks.Task<VideoClub.ServicioVideoClubPeliculasRef.Pel> EliminarAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVideoClubPeliculas/RVP", ReplyAction="http://tempuri.org/IServicioVideoClubPeliculas/RVPResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VideoClub.ServicioVideoClubPeliculasRef.PelFault), Action="http://tempuri.org/IServicioVideoClubPeliculas/RVPPelFaultFault", Name="PelFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioViedoClubPeliculas")]
        VideoClub.ServicioVideoClubPeliculasRef.Pel RVP(string usuario, int codigo, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVideoClubPeliculas/RVP", ReplyAction="http://tempuri.org/IServicioVideoClubPeliculas/RVPResponse")]
        System.Threading.Tasks.Task<VideoClub.ServicioVideoClubPeliculasRef.Pel> RVPAsync(string usuario, int codigo, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVideoClubPeliculas/GetCantidad", ReplyAction="http://tempuri.org/IServicioVideoClubPeliculas/GetCantidadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VideoClub.ServicioVideoClubPeliculasRef.PelFault), Action="http://tempuri.org/IServicioVideoClubPeliculas/GetCantidadPelFaultFault", Name="PelFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioViedoClubPeliculas")]
        VideoClub.ServicioVideoClubPeliculasRef.Pel GetCantidad(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVideoClubPeliculas/GetCantidad", ReplyAction="http://tempuri.org/IServicioVideoClubPeliculas/GetCantidadResponse")]
        System.Threading.Tasks.Task<VideoClub.ServicioVideoClubPeliculasRef.Pel> GetCantidadAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVideoClubPeliculas/GetPeliculaT", ReplyAction="http://tempuri.org/IServicioVideoClubPeliculas/GetPeliculaTResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VideoClub.ServicioVideoClubPeliculasRef.PelFault), Action="http://tempuri.org/IServicioVideoClubPeliculas/GetPeliculaTPelFaultFault", Name="PelFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioViedoClubPeliculas")]
        VideoClub.ServicioVideoClubPeliculasRef.Pel GetPeliculaT(string titulo, string genero, string año, string actor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVideoClubPeliculas/GetPeliculaT", ReplyAction="http://tempuri.org/IServicioVideoClubPeliculas/GetPeliculaTResponse")]
        System.Threading.Tasks.Task<VideoClub.ServicioVideoClubPeliculasRef.Pel> GetPeliculaTAsync(string titulo, string genero, string año, string actor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioVideoClubPeliculasChannel : VideoClub.ServicioVideoClubPeliculasRef.IServicioVideoClubPeliculas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioVideoClubPeliculasClient : System.ServiceModel.ClientBase<VideoClub.ServicioVideoClubPeliculasRef.IServicioVideoClubPeliculas>, VideoClub.ServicioVideoClubPeliculasRef.IServicioVideoClubPeliculas {
        
        public ServicioVideoClubPeliculasClient() {
        }
        
        public ServicioVideoClubPeliculasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioVideoClubPeliculasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioVideoClubPeliculasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioVideoClubPeliculasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VideoClub.ServicioVideoClubPeliculasRef.Pel GetPelicula(int codigo) {
            return base.Channel.GetPelicula(codigo);
        }
        
        public System.Threading.Tasks.Task<VideoClub.ServicioVideoClubPeliculasRef.Pel> GetPeliculaAsync(int codigo) {
            return base.Channel.GetPeliculaAsync(codigo);
        }
        
        public VideoClub.ServicioVideoClubPeliculasRef.Pel Insertar(int codigo, string titulo, string añofilm, string directores, string actores, string Loriginal, string Ldisponible, string duracion, string genero, int disponibles) {
            return base.Channel.Insertar(codigo, titulo, añofilm, directores, actores, Loriginal, Ldisponible, duracion, genero, disponibles);
        }
        
        public System.Threading.Tasks.Task<VideoClub.ServicioVideoClubPeliculasRef.Pel> InsertarAsync(int codigo, string titulo, string añofilm, string directores, string actores, string Loriginal, string Ldisponible, string duracion, string genero, int disponibles) {
            return base.Channel.InsertarAsync(codigo, titulo, añofilm, directores, actores, Loriginal, Ldisponible, duracion, genero, disponibles);
        }
        
        public VideoClub.ServicioVideoClubPeliculasRef.Pel Eliminar(int codigo) {
            return base.Channel.Eliminar(codigo);
        }
        
        public System.Threading.Tasks.Task<VideoClub.ServicioVideoClubPeliculasRef.Pel> EliminarAsync(int codigo) {
            return base.Channel.EliminarAsync(codigo);
        }
        
        public VideoClub.ServicioVideoClubPeliculasRef.Pel RVP(string usuario, int codigo, int cantidad) {
            return base.Channel.RVP(usuario, codigo, cantidad);
        }
        
        public System.Threading.Tasks.Task<VideoClub.ServicioVideoClubPeliculasRef.Pel> RVPAsync(string usuario, int codigo, int cantidad) {
            return base.Channel.RVPAsync(usuario, codigo, cantidad);
        }
        
        public VideoClub.ServicioVideoClubPeliculasRef.Pel GetCantidad(int codigo) {
            return base.Channel.GetCantidad(codigo);
        }
        
        public System.Threading.Tasks.Task<VideoClub.ServicioVideoClubPeliculasRef.Pel> GetCantidadAsync(int codigo) {
            return base.Channel.GetCantidadAsync(codigo);
        }
        
        public VideoClub.ServicioVideoClubPeliculasRef.Pel GetPeliculaT(string titulo, string genero, string año, string actor) {
            return base.Channel.GetPeliculaT(titulo, genero, año, actor);
        }
        
        public System.Threading.Tasks.Task<VideoClub.ServicioVideoClubPeliculasRef.Pel> GetPeliculaTAsync(string titulo, string genero, string año, string actor) {
            return base.Channel.GetPeliculaTAsync(titulo, genero, año, actor);
        }
    }
}
