//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoClub.ServicioVideoClubRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Log", Namespace="http://schemas.datacontract.org/2004/07/ServicioVideoClub")]
    [System.SerializableAttribute()]
    public partial class Log : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TidentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string domicilioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Finicio {
            get {
                return this.FinicioField;
            }
            set {
                if ((object.ReferenceEquals(this.FinicioField, value) != true)) {
                    this.FinicioField = value;
                    this.RaisePropertyChanged("Finicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tidentificacion {
            get {
                return this.TidentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TidentificacionField, value) != true)) {
                    this.TidentificacionField = value;
                    this.RaisePropertyChanged("Tidentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bloqueado {
            get {
                return this.bloqueadoField;
            }
            set {
                if ((this.bloqueadoField.Equals(value) != true)) {
                    this.bloqueadoField = value;
                    this.RaisePropertyChanged("bloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseñaField, value) != true)) {
                    this.contraseñaField = value;
                    this.RaisePropertyChanged("contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string domicilio {
            get {
                return this.domicilioField;
            }
            set {
                if ((object.ReferenceEquals(this.domicilioField, value) != true)) {
                    this.domicilioField = value;
                    this.RaisePropertyChanged("domicilio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoUsuarioField, value) != true)) {
                    this.tipoUsuarioField = value;
                    this.RaisePropertyChanged("tipoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioVideoClub")]
    [System.SerializableAttribute()]
    public partial class LogFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioVideoClubRef.IServicioLog")]
    public interface IServicioLog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLog/GetLog", ReplyAction="http://tempuri.org/IServicioLog/GetLogResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VideoClub.ServicioVideoClubRef.LogFault), Action="http://tempuri.org/IServicioLog/GetLogLogFaultFault", Name="LogFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioVideoClub")]
        VideoClub.ServicioVideoClubRef.Log GetLog(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLog/GetLog", ReplyAction="http://tempuri.org/IServicioLog/GetLogResponse")]
        System.Threading.Tasks.Task<VideoClub.ServicioVideoClubRef.Log> GetLogAsync(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLog/Insertar", ReplyAction="http://tempuri.org/IServicioLog/InsertarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VideoClub.ServicioVideoClubRef.LogFault), Action="http://tempuri.org/IServicioLog/InsertarLogFaultFault", Name="LogFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioVideoClub")]
        VideoClub.ServicioVideoClubRef.Log Insertar(string usuario, string contraseña, string tipoUsuario, string nombre, string domicilio, string Tidentificacion, string Finicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLog/Insertar", ReplyAction="http://tempuri.org/IServicioLog/InsertarResponse")]
        System.Threading.Tasks.Task<VideoClub.ServicioVideoClubRef.Log> InsertarAsync(string usuario, string contraseña, string tipoUsuario, string nombre, string domicilio, string Tidentificacion, string Finicio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioLogChannel : VideoClub.ServicioVideoClubRef.IServicioLog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioLogClient : System.ServiceModel.ClientBase<VideoClub.ServicioVideoClubRef.IServicioLog>, VideoClub.ServicioVideoClubRef.IServicioLog {
        
        public ServicioLogClient() {
        }
        
        public ServicioLogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioLogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VideoClub.ServicioVideoClubRef.Log GetLog(string usuario, string contraseña) {
            return base.Channel.GetLog(usuario, contraseña);
        }
        
        public System.Threading.Tasks.Task<VideoClub.ServicioVideoClubRef.Log> GetLogAsync(string usuario, string contraseña) {
            return base.Channel.GetLogAsync(usuario, contraseña);
        }
        
        public VideoClub.ServicioVideoClubRef.Log Insertar(string usuario, string contraseña, string tipoUsuario, string nombre, string domicilio, string Tidentificacion, string Finicio) {
            return base.Channel.Insertar(usuario, contraseña, tipoUsuario, nombre, domicilio, Tidentificacion, Finicio);
        }
        
        public System.Threading.Tasks.Task<VideoClub.ServicioVideoClubRef.Log> InsertarAsync(string usuario, string contraseña, string tipoUsuario, string nombre, string domicilio, string Tidentificacion, string Finicio) {
            return base.Channel.InsertarAsync(usuario, contraseña, tipoUsuario, nombre, domicilio, Tidentificacion, Finicio);
        }
    }
}
