//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoClub.ServicioVideoClubBlo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Blo", Namespace="http://schemas.datacontract.org/2004/07/ServicioVideoClubBlo")]
    [System.SerializableAttribute()]
    public partial class Blo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TidentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string domicilioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Finicio {
            get {
                return this.FinicioField;
            }
            set {
                if ((object.ReferenceEquals(this.FinicioField, value) != true)) {
                    this.FinicioField = value;
                    this.RaisePropertyChanged("Finicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tidentificacion {
            get {
                return this.TidentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TidentificacionField, value) != true)) {
                    this.TidentificacionField = value;
                    this.RaisePropertyChanged("Tidentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bloqueado {
            get {
                return this.bloqueadoField;
            }
            set {
                if ((this.bloqueadoField.Equals(value) != true)) {
                    this.bloqueadoField = value;
                    this.RaisePropertyChanged("bloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseñaField, value) != true)) {
                    this.contraseñaField = value;
                    this.RaisePropertyChanged("contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string domicilio {
            get {
                return this.domicilioField;
            }
            set {
                if ((object.ReferenceEquals(this.domicilioField, value) != true)) {
                    this.domicilioField = value;
                    this.RaisePropertyChanged("domicilio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoUsuarioField, value) != true)) {
                    this.tipoUsuarioField = value;
                    this.RaisePropertyChanged("tipoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BloFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioVideoClubBlo")]
    [System.SerializableAttribute()]
    public partial class BloFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioVideoClubBlo.IServicioBlo")]
    public interface IServicioBlo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBlo/GetBlo", ReplyAction="http://tempuri.org/IServicioBlo/GetBloResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VideoClub.ServicioVideoClubBlo.BloFault), Action="http://tempuri.org/IServicioBlo/GetBloBloFaultFault", Name="BloFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioVideoClubBlo")]
        VideoClub.ServicioVideoClubBlo.Blo GetBlo(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBlo/GetBlo", ReplyAction="http://tempuri.org/IServicioBlo/GetBloResponse")]
        System.Threading.Tasks.Task<VideoClub.ServicioVideoClubBlo.Blo> GetBloAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBlo/Bloquear", ReplyAction="http://tempuri.org/IServicioBlo/BloquearResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VideoClub.ServicioVideoClubBlo.BloFault), Action="http://tempuri.org/IServicioBlo/BloquearBloFaultFault", Name="BloFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioVideoClubBlo")]
        VideoClub.ServicioVideoClubBlo.Blo Bloquear(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBlo/Bloquear", ReplyAction="http://tempuri.org/IServicioBlo/BloquearResponse")]
        System.Threading.Tasks.Task<VideoClub.ServicioVideoClubBlo.Blo> BloquearAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBlo/Desb", ReplyAction="http://tempuri.org/IServicioBlo/DesbResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VideoClub.ServicioVideoClubBlo.BloFault), Action="http://tempuri.org/IServicioBlo/DesbBloFaultFault", Name="BloFault", Namespace="http://schemas.datacontract.org/2004/07/ServicioVideoClubBlo")]
        VideoClub.ServicioVideoClubBlo.Blo Desb(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBlo/Desb", ReplyAction="http://tempuri.org/IServicioBlo/DesbResponse")]
        System.Threading.Tasks.Task<VideoClub.ServicioVideoClubBlo.Blo> DesbAsync(string usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioBloChannel : VideoClub.ServicioVideoClubBlo.IServicioBlo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioBloClient : System.ServiceModel.ClientBase<VideoClub.ServicioVideoClubBlo.IServicioBlo>, VideoClub.ServicioVideoClubBlo.IServicioBlo {
        
        public ServicioBloClient() {
        }
        
        public ServicioBloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioBloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VideoClub.ServicioVideoClubBlo.Blo GetBlo(string usuario) {
            return base.Channel.GetBlo(usuario);
        }
        
        public System.Threading.Tasks.Task<VideoClub.ServicioVideoClubBlo.Blo> GetBloAsync(string usuario) {
            return base.Channel.GetBloAsync(usuario);
        }
        
        public VideoClub.ServicioVideoClubBlo.Blo Bloquear(string usuario) {
            return base.Channel.Bloquear(usuario);
        }
        
        public System.Threading.Tasks.Task<VideoClub.ServicioVideoClubBlo.Blo> BloquearAsync(string usuario) {
            return base.Channel.BloquearAsync(usuario);
        }
        
        public VideoClub.ServicioVideoClubBlo.Blo Desb(string usuario) {
            return base.Channel.Desb(usuario);
        }
        
        public System.Threading.Tasks.Task<VideoClub.ServicioVideoClubBlo.Blo> DesbAsync(string usuario) {
            return base.Channel.DesbAsync(usuario);
        }
    }
}
